sudo: required

language: go

services:
  - docker

build:
  provider: script
  script: docker build -t r3nic1e/chcleaner:$TRAVIS_TAG .
  on:
    tags: true

deploy:
  provider: script
  script: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin && docker push r3nic1e/chcleaner:$TRAVIS_TAG
  on:
    tags: true
